First, we import everything we will need to run the code. We will use the package autoreload to reload the changes done in the files automatically. This is followed by the general import commands (import datastructures) to make use of functions defined in datastructures.py 

In [12]:
%load_ext autoreload
%autoreload 1
%aimport datastructures
import datastructures

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


We define some basic vectors that we will be working with in the upcoming sections.

In [13]:
v1, v2, M = datastructures.define_structures()
print(f'v1 : {v1}')
print(f'v2 : {v2}')
print(f'M : {M}')

v1 : [1 1 2]
v2 : [4 2 9]
M : [[1 2 2]
 [2 0 1]
 [9 0 4]]


-----

Now, we generate a sequence with step size 0.25 from the minimum and maximum of matrix M.

In [14]:
seq = datastructures.sequence(M)
print(seq)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75
 7.   7.25 7.5  7.75 8.   8.25 8.5  8.75 9.  ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75
 7.   7.25 7.5  7.75 8.   8.25 8.5  8.75 9.  ]


-----

Last but not least, we can also define block matrices or other more complex arrays. Example a 15x9 matrix.

In [15]:
mm = datastructures.matrix(M)
print(mm.shape)
print(mm)

(15, 9)
[[1 2 2 0 0 0 1 2 2]
 [2 0 1 0 0 0 2 0 1]
 [9 0 4 0 0 0 9 0 4]
 [0 0 0 1 2 2 0 0 0]
 [0 0 0 2 0 1 0 0 0]
 [0 0 0 9 0 4 0 0 0]
 [1 2 2 0 0 0 1 2 2]
 [2 0 1 0 0 0 2 0 1]
 [9 0 4 0 0 0 9 0 4]
 [0 0 0 1 2 2 0 0 0]
 [0 0 0 2 0 1 0 0 0]
 [0 0 0 9 0 4 0 0 0]
 [1 2 2 0 0 0 1 2 2]
 [2 0 1 0 0 0 2 0 1]
 [9 0 4 0 0 0 9 0 4]]


### Implementation of numpy-functions

Understanding numpy functions by implementing them myself.

First we want to implement the function dot_product(v1,v2) that computes the dot-product of two 3-element vectors. 

In [16]:
dot = datastructures.dot_product(v1,v2)
print(dot)

24


----

To proceed we are going to implement the function cross_product(v1,v2) that computes the cross-product of two 3-element vectors.

In [17]:
cross = datastructures.cross_product(v1,v2)
print(cross)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


----

Now we want to make the computation more general and replace one vector with a matrix. In this task we are going to implement the function vector_X_matrix(v,M) that multiplies a 3-element vector from the left with a 3x3 matrix.

In [18]:
vec_X_mat = datastructures.vector_X_matrix(v1,M)
print(vec_X_mat)

[21  2 11]


----

Next we are going to perform a similar multiplication but from the other side. The function matrix_X_vector(v,M) multiplies a 3-element vector from the right with a 3x3 matrix.

In [19]:
mat_X_vec = datastructures.matrix_X_vector(M,v2)
print(mat_X_vec)

[26 17 72]


----

In this task we are going to replace both vectors with matrices. The function matrix_X_matrix(M1,M2) multiplies two 3x3 matrices. M2 should be multiplied from the left with M1.

In [20]:
mat_X_mat = datastructures.matrix_X_matrix(M, M.transpose())
print(mat_X_mat)

[[ 9  4 17]
 [ 4  5 22]
 [17 22 97]]


----

Last but not least we are going to perform a different way of multiplying two matrices. The function matrix_Xc_matrix(M1,M2) multplies the matrices M1 and M2 componentwise (Hadamard-product). Hence, every element of M1 is going to be mulitplied with every element of M2 that has the same coordinate.

In [21]:
mat_Xc_mat = datastructures.matrix_Xc_matrix(M, M.transpose())
print(mat_Xc_mat)

[[1, 4, 18], [4, 0, 0], [18, 0, 16]]
